# Generated by Django 4.2.7 on 2025-06-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_project_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuoteRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("company", models.CharField(blank=True, max_length=200)),
                (
                    "project_type",
                    models.CharField(
                        choices=[
                            ("Residential", "Residential"),
                            ("Commercial", "Commercial"),
                            ("Industrial", "Industrial"),
                            ("Renovation", "Renovation"),
                            ("Landscaping", "Landscaping"),
                            ("Interior Design", "Interior Design"),
                            ("Other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("project_description", models.TextField()),
                (
                    "budget_range",
                    models.CharField(
                        choices=[
                            ("Under $50k", "Under $50,000"),
                            ("$50k-$100k", "$50,000 - $100,000"),
                            ("$100k-$250k", "$100,000 - $250,000"),
                            ("$250k-$500k", "$250,000 - $500,000"),
                            ("$500k-$1M", "$500,000 - $1,000,000"),
                            ("Over $1M", "Over $1,000,000"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "timeline",
                    models.CharField(
                        choices=[
                            ("Immediate", "Immediate (Within 1 month)"),
                            ("1-3 months", "1-3 months"),
                            ("3-6 months", "3-6 months"),
                            ("6-12 months", "6-12 months"),
                            ("Over 1 year", "Over 1 year"),
                        ],
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(max_length=200)),
                ("additional_requirements", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_processed", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
