# Generated by Django 4.2.7 on 2025-07-01 08:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_quoterequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
