# Generated by Django 4.2.7 on 2025-07-01 08:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_project_image_url_service_image_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="image_url",
        ),
        migrations.RemoveField(
            model_name="service",
            name="image_url",
        ),
    ]
