# Generated by Django 4.2.7 on 2025-08-04 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_remove_project_image_url_remove_service_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="service",
            name="image",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
